name: shopping

services:

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - api

  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    volumes:
      - ../keys:/app/keys
    ports:
      - "5002:8080"
    networks:
      - home_infrastructure

networks:
  home_infrastructure:
    external: true