// <auto-generated />
using System;
using Home.Shopping.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Home.Shopping.Migrations
{
    [DbContext(typeof(ShoppingDbContext))]
    [Migration("20250619142224_AddMatchFragmentName")]
    partial class AddMatchFragmentName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Home.Shopping.Core.Entities.MatchFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("MatchString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MatcherGroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatcherGroupId");

                    b.ToTable("MatchFragment");
                });

            modelBuilder.Entity("Home.Shopping.Core.Entities.MatcherGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatcherGroups");
                });

            modelBuilder.Entity("Home.Shopping.Core.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddedToCartBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("InShoppingCart")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TimeAddedToCart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("Home.Shopping.Core.Entities.MatchFragment", b =>
                {
                    b.HasOne("Home.Shopping.Core.Entities.MatcherGroup", null)
                        .WithMany("MatchFragments")
                        .HasForeignKey("MatcherGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Home.Shopping.Core.Entities.MatcherGroup", b =>
                {
                    b.Navigation("MatchFragments");
                });
#pragma warning restore 612, 618
        }
    }
}
